const GET_HOSPITALS_START = 'GET_HOSPITALS_START';
const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS';
const GET_HOSPITALS_FAILURE = 'GET_HOSPITALS_FAILURE';

export { GET_HOSPITALS_START, GET_HOSPITALS_SUCCESS, GET_HOSPITALS_FAILURE };
